# On utilise une image Debian (Slim) au lieu d'Alpine pour une meilleure compatibilité
FROM node:20-slim

WORKDIR /app

# Installation des dépendances système standards (OpenSSL) avec apt-get
RUN apt-get update -y && apt-get install -y openssl ca-certificates

# Copie des fichiers de configuration
COPY package.json package-lock.json* ./

# Copie du dossier prisma AVANT l'installation
COPY prisma ./prisma

# Installation des paquets Node
RUN npm install

# Copie du reste de l'application
COPY . .

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "dev"]