// Re-export from unified domain types for backward compatibility
export type {
    CallDirection,
    CallStatus,
    EntityType,
    SortDirection,
    SortField,
    JourneyStepType,
    JourneyStepResult,
    JourneyCondition,
    JourneyConditionNode,
    JourneyGroupCondition,
    JourneyGroup,
    JourneyFilterGroup,
    JourneyFilter,
    TimeSlot,
    JourneyStep,
    AggregatedCallLog,
    CallLog,
    LogsFilters,
    LogsPagination,
    LogsSort,
    AggregatedCallLogsResponse,
    CallLogsResponse,
    ColumnVisibility,
    SegmentCategory,
    CallChainSegment,
} from "@/services/domain/call.types";
